* copia los archivos comunes

close databases
CLOSE ALL


copy file cxc_*.* to \sisadm119
copy file ccbasedatos.* to \sisadm119

copy file inv_*.* to \sisadm119
copy file ipbasedatos.* to \sisadm119

copy file cxp_*.* to \sisadm119
copy file cpbasedatos.* to \sisadm119

copy file seguridad.* to \sisadm119
copy file seguridad_maestro.* to \sisadm119
copy file libres.* to \sisadm119

copy file empresa.* to \sisadm119
copy file usuarios.* to \sisadm119
copy file conse.* to \sisadm119

copy file p_*.* to \sisadm119
